"""
Builds docs/biometric_blockchain_security_research_paper.docx programmatically
with python-docx. All figures are read from docs/research_paper/figures/
(generated by generate_figures.py from results/tables/evaluation_summary.json).
All numeric claims are sourced from that JSON and from the code-verified
implementation map assembled during repository audit -- no invented values.
"""

import json
import os

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
FIG_DIR = os.path.join(HERE, "figures")
EVAL_JSON = os.path.join(REPO_ROOT, "results", "tables", "evaluation_summary.json")
OUT_PATH = os.path.join(REPO_ROOT, "docs", "biometric_blockchain_security_research_paper.docx")

with open(EVAL_JSON, "r", encoding="utf-8") as f:
    EVAL = json.load(f)

AB = EVAL["architecture_baselines"]
BS = EVAL["biometric_stability"]

NAVY = RGBColor(0x2C, 0x3E, 0x6B)
DARK = RGBColor(0x1B, 0x1F, 0x23)

# ---------------------------------------------------------------- helpers --

def set_base_styles(doc):
    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(11)
    normal.font.color.rgb = DARK
    normal.paragraph_format.space_after = Pt(8)
    normal.paragraph_format.line_spacing = 1.15

    for name, size, color in [("Heading 1", 16, NAVY), ("Heading 2", 13, NAVY), ("Heading 3", 11.5, NAVY)]:
        st = doc.styles[name]
        st.font.name = "Times New Roman"
        st.font.size = Pt(size)
        st.font.bold = True
        st.font.color.rgb = color
        st.paragraph_format.space_before = Pt(14)
        st.paragraph_format.space_after = Pt(6)

    title = doc.styles["Title"]
    title.font.name = "Times New Roman"
    title.font.size = Pt(22)
    title.font.bold = True
    title.font.color.rgb = NAVY

    if "Caption" in [s.name for s in doc.styles]:
        cap = doc.styles["Caption"]
        cap.font.name = "Times New Roman"
        cap.font.size = Pt(9.5)
        cap.font.italic = True
        cap.font.color.rgb = DARK


def set_page_setup(doc):
    section = doc.sections[0]
    section.page_height = Cm(29.7)   # A4
    section.page_width = Cm(21.0)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)


def add_field(paragraph, instr):
    run = paragraph.add_run()
    f1 = OxmlElement("w:fldChar"); f1.set(qn("w:fldCharType"), "begin")
    it = OxmlElement("w:instrText"); it.set(qn("xml:space"), "preserve"); it.text = instr
    f2 = OxmlElement("w:fldChar"); f2.set(qn("w:fldCharType"), "end")
    run._r.append(f1); run._r.append(it); run._r.append(f2)


def add_footer_page_numbers(doc):
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run("Page ")
    add_field(p, "PAGE")
    p.add_run(" of ")
    add_field(p, "NUMPAGES")


def h1(doc, num, text):
    p = doc.add_heading(f"{num}. {text}", level=1)
    return p


def h2(doc, num, text):
    return doc.add_heading(f"{num} {text}", level=2)


def h3(doc, num, text):
    return doc.add_heading(f"{num} {text}", level=3)


def para(doc, text, italic=False, bold=False, align=None):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.italic = italic
    run.bold = bold
    if align:
        p.alignment = align
    return p


def bullet(doc, text):
    doc.add_paragraph(text, style="List Bullet")


def equation(doc, text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.font.name = "Cambria Math"
    run.font.italic = True
    run.font.size = Pt(11.5)
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after = Pt(6)
    return p


FIG_COUNTER = [0]
TAB_COUNTER = [0]


def figure(doc, filename, caption_text, width_in=5.6):
    FIG_COUNTER[0] += 1
    doc.add_picture(os.path.join(FIG_DIR, filename), width=Inches(width_in))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    cap = doc.add_paragraph()
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = cap.add_run(f"Figure {FIG_COUNTER[0]}. {caption_text}")
    run.italic = True
    run.font.size = Pt(9.5)
    return FIG_COUNTER[0]


def table(doc, caption_text, headers, rows, widths=None):
    TAB_COUNTER[0] += 1
    cap = doc.add_paragraph()
    run = cap.add_run(f"Table {TAB_COUNTER[0]}. {caption_text}")
    run.italic = True
    run.bold = True
    run.font.size = Pt(10)
    t = doc.add_table(rows=1, cols=len(headers))
    t.style = "Light Grid Accent 1"
    t.alignment = WD_TABLE_ALIGNMENT.CENTER
    hdr = t.rows[0].cells
    for i, htext in enumerate(headers):
        hdr[i].text = str(htext)
        for p in hdr[i].paragraphs:
            for r in p.runs:
                r.bold = True
                r.font.size = Pt(9.5)
    for row in rows:
        cells = t.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = str(val)
            for p in cells[i].paragraphs:
                for r in p.runs:
                    r.font.size = Pt(9.5)
    doc.add_paragraph()
    return TAB_COUNTER[0]


# ------------------------------------------------------------- build doc --

doc = Document()
set_base_styles(doc)
set_page_setup(doc)
add_footer_page_numbers(doc)

# ---- Title / Author / Abstract / Keywords ---------------------------------

t = doc.add_paragraph()
t.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = t.add_run("Biometric-Based Key Sequence Generation Using Genetic Algorithms\n"
                "for Enhanced Blockchain Security")
run.bold = True
run.font.size = Pt(20)
run.font.name = "Times New Roman"
run.font.color.rgb = NAVY

auth = doc.add_paragraph()
auth.alignment = WD_ALIGN_PARAGRAPH.CENTER
auth.paragraph_format.space_before = Pt(10)
r = auth.add_run("Fragan D'souza")
r.font.size = Pt(12.5)

doc.add_paragraph()

h2b = doc.add_paragraph()
r = h2b.add_run("Abstract")
r.bold = True
r.font.size = Pt(12)

para(doc,
     "This paper presents the design, implementation, and experimental evaluation of a biometric-driven "
     "cryptographic key generation and blockchain integrity verification system, developed as an "
     "implementation and extension of the facial-landmark-based key generation approach proposed by "
     "Sannidhan et al. [1]. The base paper combines a MobileNetV2-based facial landmark regressor, a "
     "genetic algorithm (GA) for LFSR parameter optimization, and an 8-register linear feedback shift "
     "register (LFSR) to generate cryptographic key material, reporting a dataset-level Shannon entropy "
     "of 3.24 bits over 92,706 generated sequences. Building on this foundation, the present work "
     "implements a MediaPipe Face Mesh-based landmark extraction pipeline (with a deterministic synthetic "
     "fallback), Procrustes feature normalization, a multi-objective GA for feature selection, an "
     "independently configured 32-bit Galois LFSR key-material expansion stage, RFC 5869 HKDF-SHA256 key "
     "derivation, AES-256-GCM authenticated encryption, and a proof-of-work blockchain layer that records "
     "only ciphertext hashes and never raw biometrics or secret keys. Neither the encryption nor the "
     "blockchain component exists in the base paper; both are original additions of this project. The "
     "implemented system was evaluated end-to-end: the full pipeline (106 landmarks → 212 normalized "
     "features → GA feature selection → LFSR/HKDF key derivation → AES-256-GCM encryption → "
     "blockchain integrity verification) executed successfully with a verified decrypt-and-compare round "
     "trip. A five-way baseline comparison measured byte-level Shannon entropy (approximately 7.94 bits/byte, "
     "near the 8-bit theoretical maximum) and Wald–Wolfowitz runs-test statistics across SHA-256, HKDF, "
     "GA-HKDF, and the proposed GA-LFSR-HKDF architectures, alongside a faithful re-implementation of the "
     "base paper's 8-register LFSR mechanism for direct comparison. A biometric stability study across ten "
     "synthetic subjects (five captures each) measured a 24% false-rejection rate and a 0% observed "
     "false-acceptance rate at the evaluated decision threshold, indicating a genuine reproducibility "
     "challenge for the biometric-key-regeneration approach that is disclosed rather than minimized. The "
     "results demonstrate a functioning integration of biometric feature selection, cryptographic key "
     "derivation, authenticated encryption, and blockchain-based integrity auditing, while identifying "
     "concrete limitations — including the FRR/FAR tradeoff, the deterministic nature of LFSR-based "
     "expansion, and the absence of a fuzzy-extractor mechanism — as targets for future work.")

kw = doc.add_paragraph()
r = kw.add_run("Keywords: ")
r.bold = True
kw.add_run("Biometric Cryptography; Genetic Algorithm; Facial Landmark Extraction; Linear Feedback Shift "
            "Register; HKDF-SHA256; AES-256-GCM; Blockchain Integrity Verification; Key Derivation; "
            "Biometric Key Stability")

doc.add_page_break()

# ======================================================================
# 1. INTRODUCTION
# ======================================================================
h1(doc, 1, "Introduction")

h2(doc, "1.1", "Background")
para(doc,
     "Cryptographic systems ultimately depend on the secrecy and unpredictability of their key material. "
     "Traditional key management — passwords, hardware tokens, or externally stored random seeds — "
     "introduces usability and custody burdens: keys must be remembered, stored, or physically carried, and "
     "each of these carries its own loss, theft, or forgetting risk. Biometric-driven key generation "
     "attempts to bind cryptographic material to a person's physiological characteristics so that key "
     "material can, in principle, be regenerated from the person rather than retrieved from storage. "
     "Sannidhan et al. [1] proposed one such approach for facial biometrics, combining deep-learning-based "
     "landmark extraction, genetic-algorithm parameter optimization, and an LFSR-based sequence generator "
     "to produce key material with favorable statistical randomness properties.")

h2(doc, "1.2", "Problem Statement")
para(doc,
     "The base paper [1] addresses key-sequence generation from facial features in isolation, without "
     "specifying how the generated key material would be used for actual data protection or how the "
     "integrity of protected data would be independently verifiable over time. This project addresses the "
     "downstream problem: given biometrically derived key material, how should it be used to encrypt real "
     "data with authenticated encryption, and how can the integrity of that encrypted data be verified by "
     "a third party without exposing the plaintext, the key, or the underlying biometric.")

h2(doc, "1.3", "Motivation")
para(doc,
     "A dynamic, user-specific key derived from biometric features avoids the need to store a long-term "
     "secret key directly. Combining such a key with authenticated encryption (to protect confidentiality "
     "and detect tampering at decryption time) and a tamper-evident ledger (to detect tampering "
     "independently of decryption, via publicly verifiable hash commitments) extends the base paper's "
     "scope from “key generation” to “key generation plus a usable, auditable data-protection "
     "workflow.”")

h2(doc, "1.4", "Research Gap")
para(doc,
     "Three gaps motivate this work. First, the base paper does not specify or evaluate any downstream "
     "cryptographic use of the generated key material — no encryption scheme, key-derivation step, or "
     "authenticated-encryption evaluation is presented. Second, it does not address data-integrity auditing: "
     "there is no mechanism by which a third party could later verify that protected data had not been "
     "altered. Third, the base paper's own entropy metric (3.24 bits, computed over a symbol alphabet "
     "specific to its LFSR register representation) is not evaluated using standard byte-level randomness "
     "tests (Shannon entropy in bits/byte, Wald–Wolfowitz runs test) that would allow direct comparison "
     "against conventional cryptographic key-derivation baselines such as HMAC-based Extract-and-Expand Key "
     "Derivation (HKDF).")

h2(doc, "1.5", "Objectives")
bullet(doc, "Objective 1: Develop a secure cryptographic framework that generates dynamic, user-specific "
            "encryption key material from facial biometrics using Genetic Algorithms, with emphasis on "
            "uniqueness, robustness, stability, and entropy.")
bullet(doc, "Objective 2: Use the generated cryptographic key material for data encryption and integrate "
            "the encrypted-data workflow with blockchain operations for immutable/decentralized data "
            "management and integrity verification.")
bullet(doc, "Objective 3: Address limitations of conventional cryptographic approaches by combining "
            "biometric-driven key generation, adaptive optimization, cryptographic key derivation, "
            "authenticated encryption, and blockchain-based integrity verification.")

h2(doc, "1.6", "Contributions")
bullet(doc, "An end-to-end, code-verified pipeline integrating facial-landmark feature selection (via a "
            "multi-objective GA), LFSR-based key-material expansion, HKDF-SHA256 key derivation, "
            "AES-256-GCM authenticated encryption, and a proof-of-work blockchain integrity ledger.")
bullet(doc, "A five-way controlled comparison isolating the marginal statistical effect of each pipeline "
            "stage (SHA-256 only; HKDF only; GA + HKDF; the full proposed GA-LFSR-HKDF chain; and a faithful "
            "re-implementation of the base paper's own 8-register LFSR mechanism) under an identical "
            "measurement methodology.")
bullet(doc, "An explicit, code-verified account of every implementation adaptation from the base paper, "
            "including the landmark-extraction substitution and the two functionally distinct LFSR "
            "mechanisms used in this codebase.")
bullet(doc, "An honest biometric-stability evaluation (intra-/inter-subject distance, FRR, FAR) that "
            "discloses the current reproducibility limitation rather than presenting the system as "
            "production-ready authentication.")
para(doc,
     "Within the scope of this project, these contributions are best characterized as an engineering "
     "integration and extension of an existing key-generation technique into a complete, auditable "
     "data-protection workflow, rather than as a new cryptographic primitive.")

doc.add_page_break()

# ======================================================================
# 2. RELATED WORK
# ======================================================================
h1(doc, 2, "Related Work")
para(doc,
     "This section summarizes the prior work identified and cited by the base paper [1], which forms the "
     "scientific lineage of the key-generation technique this project builds on.")

h2(doc, "2.1", "Biometric Cryptography")
para(doc,
     "Early work explored combining cryptography with biometrics directly, using fingerprint sensors, "
     "passwords, or facial images as sources of key material [2], [3]. A recurring limitation across this "
     "line of work is dependence on additional hardware (e.g., fingerprint sensors) or on features that are "
     "not robust to environmental capture noise.")

h2(doc, "2.2", "Facial Feature-Based Key Generation")
para(doc,
     "Deep-learning-based facial feature extraction has been used both for privacy protection in cloud "
     "platforms [2] and, more directly, as a source of key material for stream ciphers using SURF feature "
     "descriptors [4] — the authors' own earlier system, which the base paper explicitly improves upon "
     "by replacing SURF-based extraction with a trained MobileNetV2 landmark regressor to reduce repetitive "
     "sequence generation.")

h2(doc, "2.3", "Genetic Algorithms in Feature Optimization")
para(doc,
     "Genetic algorithms have been applied to pseudo-random number generation [5], DNA-cryptography key "
     "generation [6], and elliptic-curve key optimization [7]. The base paper's own comparison baseline, "
     "Sudeepa et al.'s GA-based key sequence generator [8], is used directly as one of the base paper's "
     "quantitative comparison points and is likewise used conceptually here to frame the GA-HKDF baseline "
     "evaluated in Section 7.")

h2(doc, "2.4", "LFSR-Based Pseudo-Random Generation")
para(doc,
     "Linear feedback shift registers remain a common building block for lightweight sequence generation, "
     "including LFSR with Gaussian-distributed feedback [9] and LFSR-driven 3D Playfair ciphers [10]. A "
     "well-known property of LFSRs, acknowledged throughout this literature, is that their output is fully "
     "determined by the register's initial state and feedback structure — an LFSR alone provides no "
     "cryptographic secrecy if an attacker recovers the seed and taps.")

h2(doc, "2.5", "Cryptographic Key Derivation")
para(doc,
     "Standardized key-derivation functions such as HKDF (RFC 5869) [12] are designed to convert non-uniform "
     "input key material into cryptographically strong, uniformly distributed key bytes via an "
     "HMAC-based Extract-and-Expand construction. HKDF is not evaluated or used anywhere in the base paper "
     "[1]; its use in this project is an original addition intended to standardize the final key-derivation "
     "step regardless of upstream biometric noise.")

h2(doc, "2.6", "Authenticated Encryption")
para(doc,
     "AES-256 in Galois/Counter Mode (GCM), standardized in FIPS 197 [13] and NIST SP 800-38D [14], provides "
     "both confidentiality and integrity/authenticity in a single primitive via an authentication tag. Like "
     "HKDF, AES-256-GCM does not appear anywhere in the base paper and is an original addition of this "
     "project.")

h2(doc, "2.7", "Blockchain-Based Integrity")
para(doc,
     "Blockchain ledgers provide tamper-evident, append-only records through cryptographic hash chaining and "
     "proof-of-work consensus. Using a blockchain purely as a metadata/integrity layer — storing only a "
     "hash commitment to encrypted data rather than the data itself — is a common pattern for combining "
     "off-chain confidentiality with on-chain auditability. This layer, too, is entirely absent from the "
     "base paper and is an original addition of this project.")

h2(doc, "2.8", "Research Gap")
para(doc,
     "No work identified in the base paper's own literature review, nor the base paper itself, evaluates the "
     "combination of (i) GA-optimized biometric feature selection, (ii) standardized HKDF key derivation, "
     "(iii) authenticated encryption, and (iv) blockchain-based integrity verification as a single, "
     "end-to-end, experimentally validated pipeline. This is the gap this project addresses.")

doc.add_page_break()

# ======================================================================
# 3. BASE PAPER AND MOTIVATION
# ======================================================================
h1(doc, 3, "Base Paper and Motivation")

h2(doc, "3.1", "Base Paper Methodology")
para(doc,
     "Sannidhan et al. [1] (“Genetic algorithms and deep learning for unique facial landmark-based key "
     "generation,” Computers and Electrical Engineering, vol. 118, article 109427, 2024) propose a "
     "three-module pipeline. A MobileNetV2 convolutional neural network, trained on 224×224 input images "
     "with the Adam optimizer (learning rate 0.0001), regresses 106 facial landmark coordinates directly "
     "from a face image. The (x, y) coordinates of each landmark are fused into a single scalar via the "
     "Cantor pairing function. A genetic algorithm (population size 100, 1000 generations, two-point "
     "crossover at rate 0.8, random-resetting mutation at rate 0.05, steady-state parent selection) then "
     "optimizes 8 register seed values for an LFSR. The LFSR itself holds 8 registers X0…X7; each "
     "iteration computes a new value from the sum of the even-indexed registers modulo 256, shifts all "
     "registers down by one position, and inserts the new value into X7, using feedback polynomial "
     "x⁷+x⁵+x³+x+1. Iterating this process for each of 74 distinct GA-optimized seed pairs "
     "produced 92,706 total sequences (up to 1287 sequences per seed) across four public face datasets "
     "(LFW [16], FERET [17], Extended Yale Face B [18], CMU Multi-PIE [19]).")

h2(doc, "3.2", "Relevant Characteristics")
para(doc,
     "The base paper reports a Shannon entropy of 3.24 bits for its generated sequence dataset (computed "
     "over the register-value alphabet used by its own LFSR representation, not a byte-level entropy in "
     "the 0–8 bits/byte sense used elsewhere in cryptographic randomness testing), an average Pearson "
     "correlation coefficient of 0.1554 across ten sample sets, and a runs-test Z-statistic of 1.6083. It "
     "compares its total-sequences and Z-statistic figures against three prior LFSR-based systems, including "
     "its own earlier SURF-feature-based system [4].")

h2(doc, "3.3", "Limitations / Opportunities Identified")
para(doc,
     "The base paper is explicitly scoped to secret-key generation; it states in its own conclusion that no "
     "storage, transmission, or downstream cryptographic-use security is addressed, and lists quantum-safe "
     "key distribution, cross-modal biometric extension, and industry deployment as future work. It also "
     "discloses that its datasets and code are not publicly available (“The authors do not have "
     "permission to share data”), which motivates an independent re-implementation rather than direct "
     "reuse of the original artifacts.")

h2(doc, "3.4", "Motivation for Our Adaptation")
para(doc,
     "Given the above, this project treats the base paper's GA + LFSR key-generation concept as a starting "
     "point, re-implements its core mechanism for direct experimental comparison (Section 5.5), and then "
     "extends the pipeline downstream into an actual data-protection workflow: HKDF key derivation, "
     "AES-256-GCM encryption, and blockchain-based integrity verification — none of which exist in the "
     "cited work.")

doc.add_page_break()

# ======================================================================
# 4. PROPOSED SYSTEM
# ======================================================================
h1(doc, 4, "Proposed System")

h2(doc, "4.1", "System Overview")
para(doc,
     "The implemented system takes either a face image or a synthetic/direct landmark array as input and "
     "produces an authenticated ciphertext together with a blockchain transaction recording a tamper-evident "
     "hash commitment to that ciphertext. Figure 1 shows the ten pipeline stages in order.")
figure(doc, "fig1_overall_architecture.png", "Overall system architecture.", width_in=4.6)

h2(doc, "4.2", "Overall Architecture")
para(doc,
     "The pipeline is organized into five functional groups: biometric feature extraction and normalization "
     "(Section 4.3–4.4), genetic-algorithm feature optimization (Section 4.5), key-material generation "
     "(Section 4.6–4.8), authenticated encryption (Section 4.9), and blockchain integrity management "
     "(Section 4.10–4.11).")

h2(doc, "4.3", "Facial Feature Extraction")
para(doc,
     "Facial landmarks are extracted using Google MediaPipe Face Mesh, which regresses 468 3D landmark "
     "points from an input image. This codebase uniformly downsamples those 468 points to 106 canonical "
     "coordinates via NumPy's linspace-based index selection. If MediaPipe is unavailable or fails to detect "
     "a face, a deterministic synthetic 106-point anatomical landmark generator is used as a fallback, built "
     "from image-derived statistics as a seed. Figure 2 details this stage together with the normalization "
     "stage that follows it.")
figure(doc, "fig2_biometric_pipeline.png", "Detailed biometric processing pipeline.", width_in=6.0)

h2(doc, "4.4", "Feature Normalization")
para(doc,
     "The 106 (x, y) landmark coordinates are normalized using a Procrustes-style transform: centroid "
     "subtraction removes translation, root-mean-square (RMS) distance scaling removes overall scale, and "
     "singular value decomposition (SVD) of the landmark covariance matrix estimates and removes a global "
     "in-plane rotation. Coordinates are then rescaled to the fixed bounding-box range [−1, 1]. The "
     "resulting 106×2 = 212-dimensional vector is the normalized feature representation used by every "
     "downstream stage.")
equation(doc, "μ = mean(P);   P′ = P − μ          (centroid subtraction)")
equation(doc, "s = √(mean(‖P′‖²));   P″ = P′ / s          (RMS scale normalization)")
equation(doc, "R = SVD-derived rotation of cov(P″);   P‴ = R·P″          (SVD rotation alignment)")

h2(doc, "4.5", "Genetic Algorithm")
para(doc,
     "A binary chromosome of length 212 (one bit per normalized feature) is evolved over a fixed 30 "
     "generations with a population of 50, tournament selection (tournament size 3), uniform crossover "
     "(rate 0.8), bit-flip mutation (rate 0.05), and elitism (top 2 chromosomes preserved unchanged each "
     "generation). Every chromosome is constrained to have at least 4 active bits. Figure 3 shows the "
     "generational loop.")
figure(doc, "fig3_ga_workflow.png", "Genetic Algorithm feature-selection workflow.", width_in=4.3)
para(doc,
     "The multi-objective fitness function combines four independently computed terms:")
equation(doc, "F(C) = w₁·F_intra + w₂·F_inter + w₃·F_entropy − w₄·F_corr")
para(doc,
     "with weights (w₁, w₂, w₃, w₄) = (0.35, 0.35, 0.15, 0.15). F_intra rewards low average "
     "Euclidean distance between multiple captures of the same subject (feature stability); F_inter rewards "
     "high average distance between different subjects (discriminability), normalized by feature-set size; "
     "F_entropy is a normalized Shannon entropy of the pooled, masked feature values across a 10-bin "
     "histogram; F_corr is the average absolute Pearson correlation across the masked feature set and is "
     "subtracted as a redundancy penalty. It is important to note that the GA optimizes a feature-selection "
     "mask for downstream key derivation — it does not itself provide cryptographic security, and its "
     "fitness terms are statistical proxies for feature quality, not security guarantees.")

h2(doc, "4.6", "Seed Generation")
para(doc,
     "The GA-selected feature subset is serialized deterministically as big-endian IEEE-754 double-precision "
     "floating-point values, appended to a fixed application salt, and hashed with SHA-256 to produce a "
     "32-byte digest. A 32-bit integer seed is derived from the first 4 bytes of this digest (substituting a "
     "fixed non-zero constant if the extracted value would be zero, since a zero-state LFSR never produces "
     "output).")

h2(doc, "4.7", "LFSR Key-Material Generation")
para(doc,
     "The proposed pipeline's key path uses a 32-bit Galois-configuration LFSR with feedback taps at "
     "positions (32, 31, 29, 1), corresponding to the primitive polynomial x³²+x³¹+x²⁹+x¹+1. "
     "Each step outputs the current least-significant bit and advances the register via a right shift with "
     "conditional XOR feedback. Generating 64 bytes (512 bits) of output from the seed produces the key "
     "material passed to HKDF. This LFSR is deterministic: for a fixed seed and tap configuration, it always "
     "produces the same output sequence — it is a pseudo-random generator, not a source of cryptographic "
     "unpredictability on its own.")

h2(doc, "4.8", "HKDF-SHA256")
para(doc,
     "RFC 5869 HKDF-SHA256 [12] is applied to the 64-byte LFSR output to derive a uniform 256-bit (32-byte) "
     "symmetric key. HKDF's Extract step compresses the (potentially non-uniform) input key material into a "
     "pseudorandom key using HMAC with a fixed application salt; its Expand step derives output key bytes "
     "using a fixed application-context info string. In this system, HKDF's role is specifically to "
     "standardize the final key regardless of any residual statistical bias in the upstream LFSR output — "
     "it is a key-derivation step, not a mechanism for stabilizing biometric noise across captures.")
equation(doc, "PRK = HMAC-SHA256(salt, IKM)          OKM = HMAC-SHA256(PRK, info ‖ 0x01)   [32 bytes]")
para(doc, "Figure 4 summarizes the complete key-generation chain from GA-selected features to the final "
          "256-bit AES key.")
figure(doc, "fig4_key_generation_pipeline.png", "Key-generation pipeline.", width_in=6.2)

h2(doc, "4.9", "AES-256-GCM")
para(doc,
     "The derived 256-bit key is used with AES-256 in Galois/Counter Mode (via the standard `cryptography` "
     "library's `AESGCM` implementation, not a custom cipher) to authenticate-and-encrypt the plaintext "
     "payload. A fresh 96-bit (12-byte) random nonce is generated per encryption, and a 128-bit (16-byte) "
     "authentication tag is produced and verified on decryption; any modification to the ciphertext causes "
     "decryption to fail with an authentication error rather than returning corrupted plaintext.")

h2(doc, "4.10", "Blockchain Integration")
para(doc,
     "The system implements a local, single-process proof-of-work blockchain (not a distributed or "
     "public network). Each block requires a SHA-256 hash with 2 leading hexadecimal zero characters "
     "(difficulty = 2). A transaction records only a SHA-256 hash of the user ID, a SHA-256 hash of the "
     "ciphertext, a reference string to the encrypted data, and a timestamp — the raw biometric data, the "
     "derived key, and the plaintext are never written to the ledger. Figure 5 shows this workflow together "
     "with the verification path.")

h2(doc, "4.11", "Integrity Verification")
para(doc,
     "Verification recomputes the SHA-256 hash of a candidate ciphertext and compares it against the "
     "on-chain `ciphertext_hash` for the corresponding transaction, in addition to validating the block "
     "hash chain and proof-of-work prefix for every block. A mismatch is reported as tamper detected; a "
     "match is reported as integrity verified.")
figure(doc, "fig5_encryption_blockchain_workflow.png", "Encryption and blockchain integrity workflow.", width_in=5.6)

doc.add_page_break()

# ======================================================================
# 5. IMPLEMENTATION
# ======================================================================
h1(doc, 5, "Implementation")

h2(doc, "5.1", "Software Architecture")
para(doc,
     "The system is implemented in Python and organized into independent modules under `src/`: "
     "`src/biometric/` (landmark extraction and normalization), `src/optimization/` (the genetic "
     "algorithm), `src/key_generation/` (seed generation, LFSR, HKDF), `src/encryption/` (AES-256-GCM), "
     "`src/blockchain/` (block, chain, verifier), and `src/evaluation/` (statistical randomness and "
     "biometric-stability metrics). `src/pipeline.py` orchestrates the end-to-end flow and the baseline "
     "comparison suite; `src/config.py` centralizes every stage's default parameters in dataclasses.")

h2(doc, "5.2", "Module Design")
table(doc, "System components and technologies.",
      ["Component", "Module", "Technology / Library"],
      [
          ["Landmark extraction", "src/biometric/landmark_extraction.py", "MediaPipe Face Mesh; synthetic fallback"],
          ["Feature normalization", "src/biometric/preprocessing.py", "NumPy (centroid, RMS scale, SVD)"],
          ["Feature selection", "src/optimization/genetic_algorithm.py", "Custom binary GA (NumPy)"],
          ["Seed generation", "src/key_generation/seed_generator.py", "hashlib (SHA-256), struct (IEEE-754)"],
          ["Key-material expansion", "src/key_generation/lfsr.py", "Custom 32-bit Galois LFSR; 8-register base-paper LFSR"],
          ["Key derivation", "src/key_generation/key_derivation.py", "cryptography.hazmat HKDF (RFC 5869)"],
          ["Authenticated encryption", "src/encryption/aes.py", "cryptography.hazmat AESGCM"],
          ["Blockchain ledger", "src/blockchain/blockchain.py, verifier.py", "Custom PoW chain (hashlib SHA-256)"],
          ["Statistical evaluation", "src/evaluation/", "NumPy, SciPy (entropy, runs test, etc.)"],
      ])

h2(doc, "5.3", "Technology Stack")
para(doc,
     "Python 3.12; NumPy, SciPy, pandas, scikit-learn for numerical/statistical processing; the "
     "`cryptography` library for HKDF and AES-256-GCM; MediaPipe and OpenCV for optional real-image "
     "landmark extraction; pytest for the test suite; matplotlib for figure generation in this paper.")

h2(doc, "5.4", "End-to-End Workflow")
para(doc,
     "`BiometricBlockchainPipeline.process_end_to_end()` executes, in order: landmark acquisition, "
     "normalization, multi-subject GA optimization and feature-mask application, seed generation, LFSR "
     "expansion, HKDF derivation, AES-256-GCM encryption, blockchain transaction creation and mining, "
     "integrity verification, and a decrypt-and-compare round-trip check. Section 7.1 reports the values "
     "produced by a fresh execution of this method.")

h2(doc, "5.5", "Implementation Adaptations from Base Paper")
para(doc,
     "This subsection makes explicit every point where this implementation diverges from the base paper's "
     "own methodology, per the project's source-separation requirement. Table 2 summarizes the comparison "
     "at a glance before the detailed discussion below.")

table(doc, "Base paper vs. our implementation.",
      ["Component", "Base Paper (Sannidhan et al., 2024)", "Our Implementation"],
      [
          ["Landmark extraction", "Trained MobileNetV2 CNN, direct 106-point regression",
           "MediaPipe Face Mesh (468 pts) uniformly downsampled to 106, with synthetic fallback"],
          ["Feature fusion", "Cantor pairing of (x,y) into a single scalar per landmark",
           "Procrustes normalization (centroid, RMS scale, SVD rotation) to a 212-D vector"],
          ["GA population / generations", "100 / 1000", "50 / 30"],
          ["GA fitness function", "1 / (|sum − inputs| + ε)",
           "0.35 F_intra + 0.35 F_inter + 0.15 F_entropy − 0.15 F_corr"],
          ["LFSR mechanism", "8-register X0..X7, feedback poly x⁷+x⁵+x³+x+1",
           "Two mechanisms: 32-bit Galois LFSR (proposed key path) and a faithful X0..X7 "
           "re-implementation (comparison baseline only)"],
          ["Key derivation", "None (LFSR output is the key material)", "HKDF-SHA256 (RFC 5869) — original addition"],
          ["Encryption", "Not present", "AES-256-GCM — original addition"],
          ["Blockchain / integrity ledger", "Not present", "Proof-of-Work blockchain, metadata-only — original addition"],
          ["Entropy metric reported", "3.24 bits (register-symbol alphabet, 92,706 sequences)",
           "~7.94 bits/byte (byte alphabet, 3200-byte stream) — different basis, not directly comparable"],
      ])

h3(doc, "5.5.1", "Landmark extraction")
para(doc,
     "Base paper: a MobileNetV2 convolutional neural network is trained end-to-end to directly regress 106 "
     "facial landmark coordinates from a 224×224 input image. Our implementation: MediaPipe Face Mesh "
     "regresses 468 landmarks using a pretrained, general-purpose model, and this codebase uniformly "
     "downsamples those 468 points to 106 via index subsampling (`np.linspace(0, 467, 106)`) rather than a "
     "task-specific trained regression. A deterministic synthetic landmark generator serves as a fallback "
     "when no real image/MediaPipe path is available. This substitution was made because the base paper's "
     "trained model and training data are not publicly released (“The authors do not have permission to "
     "share data”), making exact reproduction impossible; MediaPipe was chosen as a practical, "
     "off-the-shelf landmark source for a 106-point representation. Reproducibility implication: any "
     "quantitative landmark-accuracy claims from the base paper (e.g., its 99.37% MobileNetV2 accuracy on "
     "LFW, Table 4 of [1]) do not transfer to this implementation and are not claimed here.")

h3(doc, "5.5.2", "Cryptographic and blockchain layer")
para(doc,
     "Base paper: no encryption scheme, key-derivation function, or blockchain component is present anywhere "
     "in [1] — its scope ends at LFSR sequence generation. Our implementation: HKDF-SHA256, AES-256-GCM, "
     "and a proof-of-work blockchain ledger are original additions built specifically for this project to "
     "turn the generated key material into a usable, auditable data-protection workflow.")

h3(doc, "5.5.3", "LFSR mechanism (two distinct implementations, used for two distinct purposes)")
para(doc,
     "This codebase contains two separate LFSR implementations. `LFSRBitGenerator` is a 32-bit Galois-style "
     "LFSR (taps 32, 31, 29, 1) used in the actual “Proposed” key-generation path (Section 4.7). "
     "`PaperLFSRSubsequenceGenerator` faithfully reproduces the base paper's own 8-register X0…X7 "
     "mechanism (Eqs. 4–6 of [1]: sum the even-indexed registers modulo 256, shift registers down, insert "
     "the new value into X7) and is used exclusively to construct the `Base_Paper_GA_LFSR` comparison "
     "baseline in Section 7 — it is never used to produce the actual AES key in the proposed pipeline. "
     "This separation lets the evaluation compare the base paper's own mechanism against this project's "
     "chosen key-generation LFSR under identical measurement conditions.")

h3(doc, "5.5.4", "GA hyperparameters")
para(doc,
     "Base paper: population size 100, 1000 generations, two-point crossover. Our implementation: population "
     "size 50, 30 generations, uniform crossover, plus elitism (2 chromosomes) and tournament selection "
     "(size 3), which the base paper's Algorithm 1 does not specify. These values were chosen for "
     "tractable runtime in this repository's evaluation suite rather than tuned to match the base paper's "
     "reported convergence curve (Fig. 6 of [1]); the base paper's convergence behavior is not reproduced or "
     "claimed here.")

doc.add_page_break()

# ======================================================================
# 6. EXPERIMENTAL METHODOLOGY
# ======================================================================
h1(doc, 6, "Experimental Methodology")

h2(doc, "6.1", "Experimental Environment")
para(doc,
     "Python 3.12.10 on Windows. Key installed package versions at evaluation time: cryptography 49.0.0, "
     "NumPy 2.5.1, SciPy 1.18.0, pandas 3.0.5, scikit-learn 1.9.0, Pillow 12.3.0. `random_seed = 42` is used "
     "throughout the codebase's default configuration (`src/config.py`) for deterministic, repeatable "
     "results.")

h2(doc, "6.2", "Input Data")
para(doc,
     "All landmark data used in the experiments reported in Section 7 is generated by this codebase's "
     "deterministic synthetic landmark generator (`generate_synthetic_subject_landmarks`), not extracted "
     "from real photographed faces. This is disclosed explicitly: `scripts/run_pipeline.py` and "
     "`scripts/run_evaluation.py` construct their inputs directly via the synthetic generator, and MediaPipe "
     "was not installed in the environment used to produce the results in this paper, so the real-image "
     "MediaPipe extraction path (Section 4.3) was not exercised for any result reported here. This is a "
     "methodological limitation, not an implementation gap — the MediaPipe code path exists and is "
     "unit-tested independently, but no real face image was processed to produce the numbers in Section 7.")

h2(doc, "6.3", "Biometric Evaluation")
para(doc,
     "A 10-subject × 5-capture synthetic dataset is constructed (`scripts/run_evaluation.py`), with each "
     "subject's captures generated from a subject-specific seed plus small Gaussian perturbation "
     "(noise_level = 0.02), then normalized identically to the main pipeline. Intra-subject and inter-subject "
     "Euclidean feature distances are computed pairwise, and false-rejection/false-acceptance rates are "
     "computed at a fixed decision threshold of 0.35 (`evaluate_biometric_stability`, called with "
     "`threshold=0.35`, which overrides that function's own default of 0.5).")

h2(doc, "6.4", "Randomness Evaluation")
para(doc,
     "Byte-level Shannon entropy and the Wald–Wolfowitz runs test are computed on 3200-byte streams "
     "(100 concatenated 32-byte keys) for each of the SHA-256, HKDF, GA-HKDF, and proposed GA-LFSR-HKDF "
     "architectures, and on the flattened output of 1287 base-paper-style LFSR iterations for the "
     "`Base_Paper_GA_LFSR` baseline. Two additional statistical tests — the NIST SP 800-22 monobit "
     "frequency test [15] and a chi-square uniformity test — along with an average pairwise Hamming "
     "distance metric, are implemented in `src/evaluation/` and unit-tested, but are not invoked by "
     "`scripts/run_evaluation.py` and therefore do not appear in the results reported in Section 7; their "
     "absence from the current results is disclosed here rather than silently omitted.")

h2(doc, "6.5", "Baseline Architectures")
para(doc, "Figure 6 shows the five construction paths evaluated, all sharing the same normalized 212-D "
          "feature input, matching the exact code paths in `run_baseline_comparisons()`.")
figure(doc, "fig6_evaluation_architecture.png", "Experimental evaluation architecture (5-way baseline comparison).", width_in=6.2)
table(doc, "Baseline architecture definitions.",
      ["Baseline", "Construction"],
      [
          ["Baseline_A_SHA256", "Raw normalized 212-D features → direct SHA-256 (no GA, no HKDF)"],
          ["Baseline_B_HKDF", "Raw normalized 212-D features → HKDF-SHA256 (no GA)"],
          ["Baseline_C_GA_HKDF", "GA-selected features → HKDF-SHA256 (no LFSR)"],
          ["Proposed_GA_LFSR_HKDF", "GA-selected features → seed → 32-bit Galois LFSR → HKDF-SHA256 (full chain)"],
          ["Base_Paper_GA_LFSR", "GA-selected features → 8-register X0..X7 LFSR (1287 iterations, no HKDF)"],
      ])

h2(doc, "6.6", "Encryption Evaluation")
para(doc,
     "The end-to-end pipeline's AES-256-GCM stage is evaluated via a decrypt-and-compare round trip: the "
     "decrypted plaintext is compared byte-for-byte against the original input to confirm correct "
     "authenticated encryption/decryption. Tamper detection is separately covered by a dedicated unit test "
     "(`test_aes_gcm_tamper_detection`) that modifies ciphertext bytes and confirms decryption raises an "
     "authentication error.")

h2(doc, "6.7", "Blockchain Integrity Evaluation")
para(doc,
     "The blockchain layer is evaluated by mining a block containing the pipeline's transaction, validating "
     "the resulting chain (hash linkage, proof-of-work prefix, and per-block hash recomputation), and then "
     "running `BlockchainVerifier.verify_ciphertext_integrity()` against the produced ciphertext to confirm "
     "an `INTEGRITY_VERIFIED` result.")

h2(doc, "6.8", "Reproducibility")
para(doc,
     "All results reported in Section 7 were produced by re-running `pytest tests/`, "
     "`python scripts/run_pipeline.py`, and `python scripts/run_evaluation.py` immediately prior to writing "
     "this paper (Appendix A gives exact commands and environment details); the evaluation values matched "
     "the previously cached `results/tables/evaluation_summary.json` byte-for-byte, confirming deterministic "
     "reproducibility under the fixed `random_seed = 42` configuration.")

doc.add_page_break()

# ======================================================================
# 7. RESULTS
# ======================================================================
h1(doc, 7, "Results")

h2(doc, "7.1", "End-to-End Pipeline")
para(doc,
     "A fresh execution of `scripts/run_pipeline.py` produced the results in Table 4. Decryption was "
     "verified to exactly match the original plaintext, and the blockchain verifier reported "
     "`INTEGRITY_VERIFIED`.")
table(doc, "End-to-end pipeline results (fresh execution).",
      ["Metric", "Value"],
      [
          ["Landmarks extracted", "106"],
          ["Normalized feature dimensionality", "212"],
          ["GA-selected feature count", "65"],
          ["Derived AES-256 key length", "32 bytes"],
          ["Decryption verified", "True"],
          ["Mined block index", "1"],
          ["Blockchain verification status", "INTEGRITY_VERIFIED"],
      ])

h2(doc, "7.2", "GA Feature Selection")
para(doc,
     f"Under the default configuration (population 50, 30 generations, weights 0.35/0.35/0.15/0.15), the GA "
     f"consistently selects 65 of the 212 available normalized features for the primary subject profile used "
     f"in the end-to-end pipeline run. Table 3 lists the exact GA configuration used to produce this result.")
table(doc, "Genetic Algorithm configuration.",
      ["Parameter", "Value"],
      [
          ["Chromosome length", "212 bits (one per normalized feature)"],
          ["Population size", "50"],
          ["Generations", "30"],
          ["Selection", "Tournament (size 3)"],
          ["Crossover", "Uniform, rate 0.8"],
          ["Mutation", "Bit-flip, rate 0.05"],
          ["Elitism", "Top 2 chromosomes"],
          ["Fitness weights (intra, inter, entropy, corr)", "0.35, 0.35, 0.15, 0.15"],
          ["Minimum active bits enforced", "4"],
      ])

h2(doc, "7.3", "Randomness Evaluation")
para(doc,
     "Figures 7 and 8 present the byte-level Shannon entropy and runs-test Z-statistics respectively for all "
     "five architectures, from the freshly regenerated `evaluation_summary.json`.")
figure(doc, "fig7_entropy_comparison.png", "Byte-level Shannon entropy comparison across architectures.", width_in=5.2)
figure(doc, "fig8_runs_test_comparison.png", "Wald–Wolfowitz runs-test Z-statistic comparison.", width_in=5.4)

h2(doc, "7.4", "Baseline Comparison")
table(doc, "Randomness and baseline comparison (N = 3200-byte stream unless noted).",
      ["Architecture", "Entropy", "Runs Z", "Runs p", "Is Random"],
      [
          ["Baseline_A_SHA256", f"{AB['Baseline_A_SHA256']['entropy_bits_per_byte']} bits/byte",
           AB['Baseline_A_SHA256']['runs_z_stat'], AB['Baseline_A_SHA256']['runs_p_value'],
           AB['Baseline_A_SHA256']['is_random']],
          ["Baseline_B_HKDF", f"{AB['Baseline_B_HKDF']['entropy_bits_per_byte']} bits/byte",
           AB['Baseline_B_HKDF']['runs_z_stat'], AB['Baseline_B_HKDF']['runs_p_value'],
           AB['Baseline_B_HKDF']['is_random']],
          ["Baseline_C_GA_HKDF", f"{AB['Baseline_C_GA_HKDF']['entropy_bits_per_byte']} bits/byte",
           AB['Baseline_C_GA_HKDF']['runs_z_stat'], AB['Baseline_C_GA_HKDF']['runs_p_value'],
           AB['Baseline_C_GA_HKDF']['is_random']],
          ["Proposed_GA_LFSR_HKDF", f"{AB['Proposed_GA_LFSR_HKDF']['entropy_bits_per_byte']} bits/byte",
           AB['Proposed_GA_LFSR_HKDF']['runs_z_stat'], AB['Proposed_GA_LFSR_HKDF']['runs_p_value'],
           AB['Proposed_GA_LFSR_HKDF']['is_random']],
          ["Base_Paper_GA_LFSR", f"{AB['Base_Paper_GA_LFSR']['entropy_bits_per_symbol']} bits/symbol*",
           AB['Base_Paper_GA_LFSR']['runs_z_stat'], AB['Base_Paper_GA_LFSR']['runs_p_value'],
           AB['Base_Paper_GA_LFSR']['is_random']],
      ])
para(doc,
     "*Base_Paper_GA_LFSR's entropy is computed over its own 0–255 register-symbol alphabet (1287 "
     "subsequences), not a 3200-byte stream, and is therefore not directly comparable in magnitude to the "
     "bits/byte figures above; both happen to fall near their respective maxima. Its runs-test result of "
     "Z = 0.0, p = 0.0, is_random = False is a measurement-code artifact rather than a demonstrated "
     "randomness failure — see Section 8.1 and Section 9.9 for a precise explanation.", italic=True)

h2(doc, "7.5", "Biometric Stability")
figure(doc, "fig9_biometric_stability.png", "Intra-subject vs. inter-subject feature distance comparison.", width_in=5.2)
table(doc, "Biometric stability results (10 subjects × 5 captures, threshold = 0.35).",
      ["Metric", "Value"],
      [
          ["Intra-subject mean distance", round(BS["intra_mean"], 4)],
          ["Intra-subject std. dev.", round(BS["intra_std"], 4)],
          ["Inter-subject mean distance", round(BS["inter_mean"], 4)],
          ["Inter-subject std. dev.", round(BS["inter_std"], 4)],
          ["False Rejection Rate (FRR)", BS["frr"]],
          ["False Acceptance Rate (FAR)", BS["far"]],
          ["Decision threshold", BS["threshold"]],
      ])

h2(doc, "7.6", "Encryption Verification")
para(doc,
     "The AES-256-GCM decrypt-and-compare round trip in the end-to-end pipeline run matched the original "
     "plaintext exactly (`decryption_correct: True`). The dedicated tamper-detection unit test confirmed "
     "that modifying any ciphertext byte causes decryption to raise an authentication-tag error rather than "
     "silently returning corrupted data.")

h2(doc, "7.7", "Blockchain Verification")
para(doc,
     "The mined block satisfied the proof-of-work requirement (SHA-256 hash with 2 leading hexadecimal "
     "zeros) and the chain-validity check passed (hash linkage and per-block hash recomputation). The "
     "integrity verifier reported `INTEGRITY_VERIFIED: Ciphertext hash matches blockchain record perfectly.`")

doc.add_page_break()

# ======================================================================
# 8. DISCUSSION
# ======================================================================
h1(doc, 8, "Discussion")

h2(doc, "8.1", "Interpretation of Results")
para(doc,
     "The generated byte streams for all four HKDF/hash-based architectures exhibited empirical Shannon "
     "entropy of approximately 7.94 bits per byte, close to the theoretical 8-bit maximum for byte-valued "
     "observations, and passed the implemented Wald–Wolfowitz runs test at the 95% confidence level "
     "(|Z| < 1.96). This indicates favorable distributional characteristics under these two specific "
     "statistical metrics. It does not, on its own, establish cryptographic unpredictability: entropy and "
     "runs-test outcomes describe statistical properties of an observed sample, not resistance to a "
     "computationally bounded adversary. The `Base_Paper_GA_LFSR` baseline's runs-test result (Z = 0.0, "
     "p = 0.0) traces to a specific, identified code path: `runs_test()` internally assumes a binary "
     "{0, 1}-valued input sequence, but `PaperLFSRSubsequenceGenerator` produces raw 0–255 integer "
     "register values, which breaks that function's internal bit-counting logic. This is a measurement-code "
     "artifact, not evidence that the base paper's LFSR mechanism itself fails a properly conducted runs "
     "test; the base paper's own reported runs-test result for its mechanism (Z = 1.6083, [1], Table 13) "
     "passes at the same significance level. This discrepancy is disclosed explicitly rather than being "
     "interpreted as a security advantage for the proposed system.")

h2(doc, "8.2", "Comparison with Baselines")
para(doc,
     "Within this repository's own measurement methodology, entropy values across Baseline_A_SHA256 through "
     "Proposed_GA_LFSR_HKDF are close to each other (7.9457 down to 7.9405 bits/byte) and all comfortably "
     "near the 8-bit ceiling; the differences between them are small relative to the measurement's own "
     "resolution and should not be read as one architecture being meaningfully “more random” than "
     "another by this metric alone. Similarly, all four runs-test Z-statistics fall well within the "
     "non-significant band, so none of the four architectures is distinguished from the others as "
     "“passing” more strongly under this specific test.")

h2(doc, "8.3", "Relationship to Base Paper")
para(doc,
     "In our implementation and evaluation, the proposed GA-LFSR-HKDF stream passed the implemented runs "
     "test, whereas the evaluated `Base_Paper_GA_LFSR` implementation did not — for the specific, "
     "code-level reason identified in Section 8.1, not because of a demonstrated deficiency in the base "
     "paper's underlying mechanism. The base paper's own entropy figure (3.24 bits, over its own "
     "register-symbol alphabet and 92,706-sequence dataset) and this repository's byte-level entropy figures "
     "(approximately 7.94 bits/byte, over a 3200-byte stream) are measured on different alphabets and sample "
     "sizes; they are not directly comparable, and no superiority claim is made in either direction based on "
     "these two numbers.")

h2(doc, "8.4", "Strengths")
bullet(doc, "A complete, working, code-verified pipeline from biometric feature selection through blockchain "
            "integrity verification, with every reported number traced to an actual re-run of the code.")
bullet(doc, "Use of standardized, well-reviewed cryptographic primitives (HKDF/RFC 5869, AES-256-GCM/FIPS "
            "197 and SP 800-38D) rather than custom cryptography for the encryption and key-derivation "
            "stages.")
bullet(doc, "A blockchain design that stores only hash commitments, never raw biometrics or secret keys, "
            "consistent with a privacy-preserving audit-layer design.")
bullet(doc, "An explicit, controlled five-way baseline comparison that isolates the marginal contribution of "
            "each pipeline stage.")

h2(doc, "8.5", "Observed Limitations")
bullet(doc, f"Biometric reproducibility: a {BS['frr']:.0%} false-rejection rate at the evaluated threshold "
            f"means that in this synthetic-subject experiment, roughly one in four same-person capture pairs "
            f"would fail to match — a meaningful usability/security tradeoff for any biometric-key-"
            f"regeneration use case, not a solved problem.")
bullet(doc, "All experimental results in this paper were produced from synthetic landmark data, not real "
            "photographed faces (Section 6.2); the MediaPipe real-image extraction path is implemented and "
            "unit-tested but was not exercised to produce any number reported here.")
bullet(doc, "The LFSR stages (both the proposed 32-bit Galois LFSR and the base-paper 8-register mechanism) "
            "are fully deterministic given their seed and configuration — an attacker who recovers the "
            "seed and structure can reproduce the output exactly.")
bullet(doc, "The blockchain layer is a local, single-process proof-of-work simulation, not a distributed or "
            "publicly deployed network; no consensus-attack, network-partition, or multi-node throughput "
            "evaluation was performed.")

doc.add_page_break()

# ======================================================================
# 9. SECURITY ANALYSIS
# ======================================================================
h1(doc, 9, "Security Analysis")

h2(doc, "9.1", "Threat Model")
para(doc,
     "The analysis assumes Kerckhoffs's principle: the attacker knows the full algorithm design (GA "
     "configuration, LFSR taps, HKDF parameters, blockchain structure) but not the specific biometric "
     "capture, the derived key, or the plaintext of any given transaction. The attacker may have read access "
     "to the blockchain ledger and to any ciphertext they intercept.")

h2(doc, "9.2", "Confidentiality")
para(doc,
     "Confidentiality of the plaintext rests entirely on the secrecy and quality of the derived AES-256 key, "
     "provided by AES-256-GCM when used correctly (unique nonce per encryption, which this implementation "
     "generates via `os.urandom(12)` by default). AES-GCM provides authenticated encryption when used "
     "correctly; it does not itself compensate for a weak or predictable key.")

h2(doc, "9.3", "Integrity")
para(doc,
     "Blockchain integrity does not provide confidentiality — it provides a tamper-evident commitment to "
     "the ciphertext's hash. An attacker who modifies stored ciphertext without also being able to alter the "
     "corresponding on-chain hash (and, for a longer chain, re-mine every subsequent block's proof-of-work) "
     "will be detected by the verifier. In this local single-process implementation, an attacker with direct "
     "access to the running process's in-memory chain could trivially alter both the ciphertext and the "
     "ledger together; the current design assumes ledger and ciphertext storage are not both fully "
     "compromised by the same attacker, a limitation of the local/simulated deployment rather than of the "
     "PoW/hash-chaining concept itself.")

h2(doc, "9.4", "Biometric Exposure")
para(doc,
     "A face is not inherently secret: it is visible in public, in photographs, and on video. Biometric "
     "features may be reproducible by anyone with access to a sufficiently similar image of the same person. "
     "This system does not attempt to treat the raw face as a secret; it never stores raw landmarks or "
     "images on the blockchain, but the security of key regeneration ultimately depends on an attacker not "
     "being able to obtain a sufficiently accurate capture of the legitimate user's face and reproduce the "
     "same GA/LFSR/HKDF pipeline.")

h2(doc, "9.5", "Key Reproducibility")
para(doc,
     f"Because feature extraction and normalization are sensitive to capture noise, and because no fuzzy "
     f"extractor or error-correcting mechanism is implemented, repeated captures of the same subject do not "
     f"reliably regenerate byte-identical key material — consistent with the measured "
     f"{BS['frr']:.0%} FRR in Section 7.5. This is disclosed as an open problem, not resolved by this "
     f"implementation.")

h2(doc, "9.6", "LFSR Security Considerations")
para(doc,
     "Both LFSR implementations in this codebase are deterministic pseudo-random sequence generators. An "
     "attacker who knows the seed and the tap/feedback configuration (which Kerckhoffs's principle assumes "
     "they do) can reproduce the LFSR output exactly. The LFSR's role in this system is sequence expansion, "
     "not a standalone source of cryptographic unpredictability; the subsequent HKDF step is what "
     "standardizes the final key, not the LFSR itself.")

h2(doc, "9.7", "Cryptographic Key Derivation")
para(doc,
     "HKDF-SHA256 is a key-derivation mechanism, not a biometric stabilizer: given consistent input key "
     "material, it reliably derives a uniform key, but it does not compensate for the input key material "
     "itself differing across captures of the same subject (Section 9.5).")

h2(doc, "9.8", "Blockchain Security Properties")
para(doc,
     "The implemented proof-of-work (difficulty 2, i.e., 2 leading hexadecimal zero characters) is a "
     "demonstration-scale parameter, not a production security parameter; it was not tuned or evaluated "
     "against any specific adversarial mining-power assumption, and no multi-node consensus or "
     "51%-attack-resistance property is claimed for this local, single-process implementation.")

h2(doc, "9.9", "Limitations of Statistical Randomness Testing")
para(doc,
     "Passing Shannon-entropy and runs-test checks provides statistical evidence about a sample's "
     "distributional properties; it does not constitute a proof of cryptographic security or "
     "unpredictability against a computationally bounded adversary, and it does not substitute for formal "
     "cryptanalysis of the key-derivation chain as a whole. The degenerate `Base_Paper_GA_LFSR` runs-test "
     "result described in Section 8.1 is a concrete illustration of how easily such tests can be "
     "misapplied to non-conforming input and produce misleading pass/fail labels if the implementation "
     "detail is not checked.")
table(doc, "Security properties and mechanisms.",
      ["Property", "Mechanism", "Provided by"],
      [
          ["Confidentiality", "Authenticated symmetric encryption", "AES-256-GCM"],
          ["Ciphertext integrity / tamper detection (at decrypt time)", "GCM authentication tag", "AES-256-GCM"],
          ["Long-term data integrity auditing", "Hash-chained, PoW-mined ledger", "Blockchain layer"],
          ["Key uniformity", "HMAC-based extract-and-expand", "HKDF-SHA256"],
          ["Biometric non-storage", "Metadata-only transactions", "Blockchain transaction schema"],
          ["Biometric noise tolerance", "Not implemented", "— (future work, Section 10)"],
          ["Liveness / anti-spoofing", "Not implemented", "— (future work, Section 10)"],
      ])

doc.add_page_break()

# ======================================================================
# 10. LIMITATIONS AND FUTURE WORK
# ======================================================================
h1(doc, 10, "Limitations and Future Work")

h2(doc, "10.1", "Limitations")
bullet(doc, f"Biometric variability and the current {BS['frr']:.0%} FRR represent an unresolved "
            f"reproducibility challenge for key regeneration from repeated captures.")
bullet(doc, "All reported experimental results use synthetic landmark data; no real-image evaluation was "
            "performed for this paper (Section 6.2).")
bullet(doc, "The MediaPipe real-image landmark path silently falls back to the synthetic generator on any "
            "failure (missing package, no face detected), which could mask capture failures in a real "
            "deployment if not explicitly monitored.")
bullet(doc, "Both LFSR mechanisms are deterministic; recovering the seed and configuration fully determines "
            "their output.")
bullet(doc, "Statistical randomness tests (Shannon entropy, runs test) do not prove cryptographic security; "
            "no formal cryptanalysis of the full key-derivation chain was performed.")
bullet(doc, "The NIST SP 800-22 monobit test, a chi-square uniformity test, and an average pairwise Hamming "
            "distance metric are implemented in `src/evaluation/` but are not currently integrated into the "
            "evaluation pipeline or reported results.")
bullet(doc, "The blockchain implementation is local and simulated (single process, PoW difficulty 2); no "
            "distributed deployment, network-level attack, or throughput/scalability evaluation was "
            "performed.")
bullet(doc, "No fuzzy extractor, error-correcting code, or other biometric key-binding technique is "
            "implemented to tolerate captures noise.")
bullet(doc, "The evaluated subject population (10 synthetic subjects for the stability study; 5 synthetic "
            "subjects for the GA training dataset) is small and synthetic, limiting generalizability to a "
            "real, diverse population.")

table(doc, "Limitations and corresponding future work.",
      ["Limitation", "Proposed Future Work"],
      [
          [f"{BS['frr']:.0%} FRR observed at threshold {BS['threshold']}; biometric key regeneration is not "
           "yet reliable across captures",
           "Investigate fuzzy extractors, error-correcting codes, or improved normalization for "
           "noise-tolerant key regeneration"],
          ["All reported results use synthetic landmark data; MediaPipe real-image path unexercised",
           "Evaluate on larger, diverse real-image datasets under the actual MediaPipe extraction path"],
          ["Both LFSR mechanisms are fully deterministic given seed/configuration",
           "Formal cryptanalysis of the full key-derivation chain beyond statistical randomness testing"],
          ["NIST monobit, chi-square, and Hamming-distance metrics implemented but not integrated into "
           "the evaluation pipeline",
           "Integrate all implemented statistical tests into the standard evaluation report"],
          ["Blockchain layer is a local, single-process PoW simulation",
           "Evaluate under real distributed deployment: throughput, network partition, consensus attacks"],
          ["Small, synthetic subject population (10 for stability study, 5 for GA training)",
           "Scale to larger, real, and more diverse subject populations"],
          ["No liveness/anti-spoofing detection",
           "Adversarial and spoofing-resistance evaluation of the capture/extraction stage"],
          ["No hardware acceleration evaluated", "Investigate hardware acceleration and scalability for real-time use"],
      ])

h2(doc, "10.2", "Future Work")
bullet(doc, "Investigate appropriate mechanisms for robust biometric key regeneration, potentially including "
            "improved alignment, normalization, more stable feature representations, or biometric "
            "key-binding techniques such as fuzzy extractors or error-correcting codes — none of which "
            "currently exist in this repository.")
bullet(doc, "Evaluate the system on larger and more diverse real-image datasets under the actual MediaPipe "
            "extraction path.")
bullet(doc, "Integrate the already-implemented but currently unused NIST SP 800-22 monobit test, chi-square "
            "uniformity test, and average pairwise Hamming distance metric into the standard evaluation "
            "report.")
bullet(doc, "Conduct a formal cryptanalytic and adversarial evaluation of the full key-derivation chain, "
            "beyond statistical randomness testing.")
bullet(doc, "Evaluate the blockchain layer under a real distributed deployment, including throughput, "
            "network-partition, and consensus-attack scenarios.")
bullet(doc, "Investigate hardware acceleration and scalability for real-time use.")
bullet(doc, "Conduct adversarial/spoofing evaluation of the biometric capture and extraction stage.")

doc.add_page_break()

# ======================================================================
# 11. CONCLUSION
# ======================================================================
h1(doc, 11, "Conclusion")
para(doc,
     "This paper documented the design, code-verified implementation, and experimental evaluation of a "
     "biometric-driven key generation and blockchain integrity verification system built as an "
     "implementation and extension of Sannidhan et al.'s facial-landmark-based key generation approach [1]. "
     "The complete proposed architecture — biometric feature extraction, genetic-algorithm feature "
     "selection, LFSR-based key-material expansion, HKDF-SHA256 key derivation, AES-256-GCM authenticated "
     "encryption, blockchain-based integrity verification, and a controlled multi-architecture evaluation "
     "— was implemented and re-verified end-to-end immediately prior to writing this paper (21 of 21 "
     "unit tests passing; pipeline execution and evaluation suite both reproducing byte-for-byte identical "
     "results to the previously cached figures). The implementation differs from the base paper specifically "
     "at the facial landmark extraction stage, where MediaPipe Face Mesh downsampling (with a synthetic "
     "fallback) replaces the base paper's custom-trained MobileNetV2 regressor, and it extends the base "
     "paper's scope entirely: no encryption or blockchain component exists in [1] at all. Within the scope "
     "of this project, the results indicate a functioning integration rather than a proven security "
     "guarantee: entropy and runs-test statistics provide favorable but limited statistical evidence, the "
     "biometric stability evaluation discloses a genuine 24% false-rejection rate that remains unresolved, "
     "and both LFSR mechanisms remain fully deterministic under Kerckhoffs's principle. These limitations "
     "are stated explicitly, alongside concrete future-work directions, rather than omitted or minimized.")

doc.add_page_break()

# ======================================================================
# REFERENCES
# ======================================================================
h1(doc, "", "References")
doc.paragraphs[-1].runs[0].text = "References"

REFERENCES = [
    "M. S. Sannidhan, J. E. Martis, K. N. Pallavi, V. Ravi, H. L. Gururaj, T. J. Alahmadi, “Genetic "
    "algorithms and deep learning for unique facial landmark-based key generation,” Computers and "
    "Electrical Engineering, vol. 118, article 109427, 2024. https://doi.org/10.1016/j.compeleceng.2024.109427",

    "X. Zhao, S. Lin, X. Chen, C. Ou, C. Liao, “Application of face image detection based on deep "
    "learning in privacy security of intelligent cloud platform,” Multimedia Tools and Applications, "
    "vol. 79, no. 23–24, pp. 16707–16718, 2020.",

    "F. Quinga-Socasi, L. Zhinin-Vera, O. Chang, “A deep learning approach for symmetric-key "
    "cryptography system,” Advances in Intelligent Systems and Computing, vol. 1288, pp. 539–552, "
    "2020.",

    "G. Panchal, D. Samanta, S. Barman, “A novel key generation approach based on facial image features "
    "for stream cipher system,” in Proc. 2020 3rd Int. Conf. Smart Systems and Inventive Technology "
    "(ICSSIT), IEEE, 2020, pp. 956–962. (Also cited as [18] in the base paper.)",

    "S. Kalsi, H. Kaur, V. Chang, “DNA cryptography and deep learning using genetic algorithm with NW "
    "algorithm for key generation,” Journal of Medical Systems, vol. 42, no. 1, 2018.",

    "F. S. Abu-Almash, “Apply genetic algorithm for pseudo random number generator,” International "
    "Journal of Advanced Research in Computer Science and Software Engineering, vol. 6, no. 8, pp. 8–19, "
    "2016.",

    "K. Shankar, P. Eswaran, “An efficient image encryption technique based on optimized key generation "
    "in ECC using genetic algorithm,” in Artificial Intelligence and Evolutionary Computations in "
    "Engineering Systems (Proc. ICAIECES 2015), Springer India, 2016, pp. 705–714.",

    "K. B. Sudeepa, G. Aithal, V. Rajinikanth, S. C. Satapathy, “Genetic algorithm based key sequence "
    "generation for cipher system,” Pattern Recognition Letters, vol. 133, pp. 341–348, 2020.",

    "G. Cotrina, A. Peinado, A. Ortiz, “Gaussian pseudorandom number generator using linear feedback "
    "shift registers in extended fields,” Mathematics, vol. 9, no. 5, p. 556, 2021.",

    "A. Kaur, H. K. Verma, R. K. Singh, “3D—Playfair cipher using LFSR based unique random number "
    "generator,” in Proc. 2013 6th Int. Conf. Contemporary Computing (IC3), IEEE, 2013, pp. 18–23.",

    "M. S. Sannidhan, K. B. Sudeepa, J. E. Martis, A. Bhandary, “A novel key generation approach based "
    "on facial image features for stream cipher system,” in Proc. 2020 3rd Int. Conf. Smart Systems and "
    "Inventive Technology (ICSSIT), IEEE, 2020, pp. 956–962.",

    "H. Krawczyk, P. Eronen, “HMAC-based Extract-and-Expand Key Derivation Function (HKDF),” IETF "
    "RFC 5869, 2010.",

    "National Institute of Standards and Technology, “Advanced Encryption Standard (AES),” FIPS "
    "Publication 197, 2001.",

    "M. Dworkin, “Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM) and "
    "GMAC,” NIST Special Publication 800-38D, 2007.",

    "A. Rukhin et al., “A Statistical Test Suite for Random and Pseudorandom Number Generators for "
    "Cryptographic Applications,” NIST Special Publication 800-22, Revision 1a, 2010.",

    "G. B. Huang, M. Mattar, T. Berg, E. Learned-Miller, “Labeled Faces in the Wild: A database for "
    "studying face recognition in unconstrained environments,” in Workshop on Faces in 'Real-Life' "
    "Images: Detection, Alignment, and Recognition, 2008.",

    "P. J. Phillips, H. Moon, S. A. Rizvi, P. J. Rauss, “The FERET evaluation methodology for "
    "face-recognition algorithms,” IEEE Transactions on Pattern Analysis and Machine Intelligence, "
    "vol. 22, no. 10, pp. 1090–1104, 2000.",

    "A. S. Georghiades, P. N. Belhumeur, D. J. Kriegman, “From few to many: illumination cone models for "
    "face recognition under variable lighting and pose,” IEEE Transactions on Pattern Analysis and "
    "Machine Intelligence, vol. 23, no. 6, pp. 643–660, 2001.",

    "R. Gross, I. Matthews, J. Cohn, T. Kanade, S. Baker, “Multi-PIE,” Image and Vision Computing, "
    "vol. 28, no. 5, pp. 807–813, 2010.",
]
for i, ref in enumerate(REFERENCES, 1):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Inches(0.3)
    p.paragraph_format.first_line_indent = Inches(-0.3)
    p.add_run(f"[{i}] {ref}").font.size = Pt(10)

doc.add_page_break()

# ======================================================================
# APPENDIX
# ======================================================================
h1(doc, "", "Appendix: Reproducibility Information")
doc.paragraphs[-1].runs[0].text = "Appendix: Reproducibility Information"

para(doc, "Environment:", bold=True)
bullet(doc, "Python 3.12.10, Windows")
bullet(doc, "cryptography 49.0.0, NumPy 2.5.1, SciPy 1.18.0, pandas 3.0.5, scikit-learn 1.9.0, Pillow 12.3.0")
bullet(doc, "requirements.txt declares: numpy>=1.24.0, scipy>=1.10.0, pandas>=2.0.0, matplotlib>=3.7.0, "
            "scikit-learn>=1.2.0, cryptography>=41.0.0, pytest>=7.3.0, pillow>=9.5.0, opencv-python>=4.7.0, "
            "mediapipe>=0.10.0")
bullet(doc, "mediapipe and opencv-python were not installed in the environment used to produce the results "
            "in this paper — all landmark data is from the synthetic generator (Section 6.2)")
bullet(doc, "random_seed = 42 (src/config.py, AppConfig)")

para(doc, "Commands used to produce every reported result:", bold=True)
p = doc.add_paragraph()
r = p.add_run("$env:PYTHONPATH='.'; pytest tests/                    # 21 passed\n"
              "$env:PYTHONPATH='.'; python scripts/run_pipeline.py    # end-to-end demo\n"
              "$env:PYTHONPATH='.'; python scripts/run_evaluation.py  # baseline + biometric-stability suite")
r.font.name = "Consolas"
r.font.size = Pt(9.5)

para(doc, "Result locations:", bold=True)
bullet(doc, "results/tables/evaluation_summary.json — baseline comparison and biometric stability values")
bullet(doc, "docs/research_paper/figures/ — all 9 figures in this paper (generated by generate_figures.py)")
bullet(doc, "tests/ — 21 unit tests across biometric, GA, LFSR, key derivation, encryption, blockchain, "
            "and evaluation modules")

doc.save(OUT_PATH)
print("Saved:", OUT_PATH)
print("Figures used:", FIG_COUNTER[0])
print("Tables used:", TAB_COUNTER[0])
print("References:", len(REFERENCES))
